name: goodloop
description: Daily Acts of Kindness App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1

  go_router: ^13.2.0

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.9
  firebase_messaging: ^14.9.4

  google_sign_in: ^6.2.1

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  confetti: ^0.7.0
  cached_network_image: ^3.3.1

  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter_timezone: ^5.0.1

  intl: ^0.19.0
  shared_preferences: ^2.2.2
  logger: ^2.0.0

  image_picker: ^1.0.7
  appwrite: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
